---

- name: install software-properties-common
  apt: name=software-properties-common 

- name: Add repo key for mariadb
  apt_repository: repo='deb [arch=amd64,i386,ppc64el] http://lon1.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu xenial main' state=present update_cache=yes

- name: Install MariaDB
  apt: name=mariadb-server state=present allow_unauthenticated=yes

- name: Start MySQL Service
  service: name=mysql state=started enabled=yes

- name: Install Python MySQL package
  apt: name=python-mysqldb


- name: create a database user
  mysql_user: name=max password=demo priv=*.*:ALL
  
